apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-svc
    app.kubernetes.io/part-of: {{ .Release.Name }}
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - nodePort: {{ .Values.service.nodePort }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  type: NodePort
