apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.image.tag }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/part-of: "Deployment-{{ .Chart.Name }}"
    spec:
      volumes:
      - name: {{ .Chart.Name }}-volume
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-volumeclaim
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Chart.Name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.port }}
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: {{ .Values.port | quote }}
        - name: ZOOKEEPER_TICK_TIME 
          valueFrom: 
            configMapKeyRef:
              name: {{ .Chart.Name }}-configmap
              key: "ZOOKEEPER_TICK_TIME"
        volumeMounts:
        - mountPath: "/var/lib/zookeeper/"
          name: {{ .Chart.Name }}-volume
          subPath: {{ .Chart.Name }}
