apiVersion: v2
name: kafka-cluster
description: A Helm chart for setting up Kafka cluster (Development environment) on Kubernetes 
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kafka-zookeeper
    version: 0.1.0
    repository: file://./charts/zookeeper
  - name: kafka-broker
    version: 0.1.0
    repository: file://./charts/kafka
  - name: kafka-gui
    version: 0.1.0
    repository: file://./charts/kafka-ui
    condition: kafka-gui.enabled
