apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-volume
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-volume
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.volume.storageCapacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: none
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.volume.nfs.path }}
    server: {{ .Values.volume.nfs.server }}
