apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-external-svc
  namespace: {{ .Release.Namespace }} 
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-external-svc
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.externalPort }}
      nodePort: {{ .Values.service.externalPort }}
      
