apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka-headless-service.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "kafka-headless-service.name" .}}
    app.kubernetes.io/part-of: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }} 
spec:
  ports:
  - port: {{ .Values.service.internalPort }}
    name: broker-port
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
