apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-svc
    app.kubernetes.io/part-of: {{ .Release.Name }}
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.service.internalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  type: ClusterIP
